#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/ant/ant 80
    chown root /opt/ant/chrome-sandbox
    chmod 4755 /opt/ant/chrome-sandbox
    echo "Run sudo xdg-settings set default-web-browser ant.desktop && sudo update-alternatives --config x-www-browser to set ant as your default browser."
    ln -sf /opt/ant/ant /usr/bin/ant
fi
